### ISSUE TITLE
图片挂了

### ISSUE THREAD

**Issue by github-lewis** [BUG9/spring-security#1]
作者你好，很喜欢你的文章，很详细很透彻，只是文章中很多图挂了，方便的话请再上传一下。谢谢！

**Comment by BUG9** [comment]
感谢你的支持，github上文章的地址我已经替换成我的掘金地址了，你也可以访问这个地址 https://juejin.im/user/5d5a172df265da03af19d1fe/posts------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;github-lewis&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月2日(星期四) 上午10:56
收件人:&nbsp;&quot;BUG9/spring-security&quot;<spring-security@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[BUG9/spring-security] 图片挂了 (#1)

**Comment by BUG9** [comment]
感谢你的支持，github上文章的地址我已经替换成我的掘金地址了，你也可以访问这个地址 https://juejin.im/user/5d5a172df265da03af19d1fe/posts

**Comment by BUG9** [comment]
感谢你的支持，github上文章的地址我已经替换成我的掘金地址了，你也可以访问这个地址 https://juejin.im/user/5d5a172df265da03af19d1fe/posts

**Comment by github-lewis** [comment]
已查到。另，是否后续你的文章只在掘金发布？小弟打算持续关注你的文章。

**Comment by BUG9** [comment]
如果以后还写的话肯定会在掘金😂😂😂------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;github-lewis&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月2日(星期四) 下午2:18
收件人:&nbsp;&quot;BUG9/spring-security&quot;<spring-security@noreply.github.com&gt;;
抄送:&nbsp;&quot;ZhaoHeCai&quot;<1161650078@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BUG9/spring-security] 图片挂了 (#1)

**Comment by github-lewis** [comment]
了！持续关注！向大哥学习！
